---
- name: Prepare
  hosts: all

  pre_tasks:
    - name: Update apt cache (on Debian).
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

  tasks:
    - name: Remove packages
      package:
        name:
          - proftpd-basic
          - proftpd-core
        state: absent
